### ISSUE TITLE
'Engine' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by riziles** [yehoshuadimarsky/bcpandas#196]
Getting this error with a brand-new install of `bcpandas`:

`'Engine' object has no attribute 'cursor'`

Had to downgrade pandas to get it to work.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue.

My environment:

```
(.venv) PS C:\Users\Gord\PycharmProjects\bcpandas_demo> python -VV
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
(.venv) PS C:\Users\Gord\PycharmProjects\bcpandas_demo> pip list
Package              Version
-------------------- -----------
bcpandas             2.6.2
greenlet             3.0.3
numpy                1.26.4
pandas               2.2.2
pip                  24.0
pip-upgrade-outdated 1.5
pyodbc               5.1.0
python-dateutil      2.9.0.post0
pytz                 2024.1
setuptools           70.0.0
six                  1.16.0
SQLAlchemy           2.0.30
typing_extensions    4.12.2
tzdata               2024.1
wheel                0.43.0
```

**Comment by riziles** [comment]
@gordthompson I installed with `mamba` which installed SqlAlchemy 1.4. This appears to be an issue with the [Conda Forge recipe](https://github.com/conda-forge/bcpandas-feedstock/blob/main/recipe/meta.yaml):

```yaml
requirements:
  host:
    - python >=3.8.1
    - pip
    - setuptools
    - poetry >=1.3.2
  run:
    - python >=3.8.1
    - pandas >=0.19
    - pyodbc
    - sqlalchemy >=1.0,<2
   ```

Maybe it's as simple as removing that "<2"?
